In [22]:
# Import the required libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
import pickle
from scipy import stats
import re

In [23]:
# Load the diabetes dataset to a pandas DataFrame
Drug_dataset = pd.read_csv('/content/ascdataset.csv')

# Print the first 5 rows of the dataset
Drug_dataset.head()

,paziente,sex,CODE,Age,Schooling,MMSE,BADL,IADL,NPIFxS,NPIstress,Adas-Cog,FAB,Outcome
0,AM,F,NA 122,72,3,14,3,1,10,5,49,8,0
1,BA,F,NP 013,78,3,8,1,0,60,20,62,3,0
2,CG,M,NP 005,69,8,20,5,2,20,10,43,6,1
3,CR,F,NA 004,63,8,20,3,0,48,30,59,6,1
4,CS,M,NA 038,75,13,11,1,0,80,60,61,5,0

In [24]:
# To get the number of rows and columns in the dataset
Drug_dataset.shape
#prints (768, 9)

# To get the statistical measures of the data
Drug_dataset.describe()

,Age,Schooling,MMSE,BADL,IADL,NPIFxS,NPIstress,Adas-Cog,FAB,Outcome
count,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000
mean,73.129032,6.935484,13.758065,2.677419,1.016129,26.306452,14.758065,46.629032,5.774194,0.500000
std,6.836459,4.015833,6.263832,1.871041,1.311887,19.811066,13.727662,13.272965,2.356848,0.504082
min,57.000000,2.000000,3.000000,0.000000,0.000000,0.000000,0.000000,16.000000,1.000000,0.000000
25%,69.250000,5.000000,9.000000,1.000000,0.000000,10.000000,2.750000,38.500000,4.000000,0.000000
50%,74.500000,5.000000,13.000000,3.000000,0.000000,24.500000,12.000000,49.000000,6.000000,0.500000
75%,78.000000,8.000000,18.750000,4.000000,2.000000,38.000000,20.000000,56.000000,7.000000,1.000000
max,91.000000,17.000000,28.000000,6.000000,5.000000,80.000000,60.000000,69.000000,12.000000,1.000000

In [25]:
# To get details of the outcome column
Drug_dataset['Outcome'].value_counts()

0    31
1    31
Name: Outcome, dtype: int64

In [26]:
# separating the data and labels
X = Drug_dataset.drop(columns = 'Outcome', axis=1)
Y = Drug_dataset['Outcome']

# To print the independent variables
print(X)

   paziente sex    CODE  Age  Schooling  MMSE  BADL  IADL  NPIFxS  NPIstress  \
0        AM   F  NA 122   72          3    14     3     1      10          5
1        BA   F  NP 013   78          3     8     1     0      60         20
2        CG   M  NP 005   69          8    20     5     2      20         10
3        CR   F  NA 004   63          8    20     3     0      48         30
4        CS   M  NA 038   75         13    11     1     0      80         60
..      ...  ..     ...  ...        ...   ...   ...   ...     ...        ...
57       SR   M  NA 060   77          5    10     3     1      12          5
58       GR   F  NA 063   77          5     8     1     0      40         25
59       TG   M  NP 023   77          8    24     4     2       0          0
60       LM   F  NA 117   61          8     6     0     0      10          5
61      RMA   F  NA 151   78          5    15     4     2      20         10

    Adas-Cog  FAB
0         49    8
1         62    3
2         43    6
3         59    6
4         61    5
..       ...  ...
57        56    8
58        55    6
59        36    7
60        53    4
61        48    7

[62 rows x 12 columns]

In [27]:
# To print the outcome variable
print(Y)

0     0
1     0
2     1
3     1
4     0
     ..
57    1
58    1
59    1
60    0
61    0
Name: Outcome, Length: 62, dtype: int64

In [28]:
#Split the data into train and test
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, stratify=Y, random_state=2)
print(X.shape, X_train.shape, X_test.shape)

(62, 12) (49, 12) (13, 12)

In [29]:
# Build the model
classifier = svm.SVC(kernel='linear')

In [11]:
# Train the support vector Machine Classifier
classifier_value = classifier.fit(X_train, Y_train)
float_value = float(classifier_value.replace('%', ''))

ValueError: ignored

In [ ]:
Value = '9.94%'

float_value = float(Value.replace('%', ''))

In [ ]:
import re

Value2 = 'xyz2.23'

Output = re.findall(r'\d+\.\d+', Value2)
print(Output)

In [ ]:
# Accuracy score on the training data
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

print('Accuracy score of the training data : ', training_data_accuracy)

# Accuracy score on the test data
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

print('Accuracy score of the test data : ', test_data_accuracy)